config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "admin/sidekiq"

  devise_for :users, skip: [:registration], controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    post "users",   to: "users/registrations#create", as: :user_registration
    get "sign_up",  to: "users/registrations#new",    as: :new_user_registration
    get "sign_in",  to: "devise/sessions#new",     as: :new_user_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end
  root "presentations#index"

  namespace :manage do
    resources :presentations, only: [:index, :create, :edit, :update, :destroy]
  end
  resources :tags, only: [:show], param: :name
  get "presentations/search"
  get "presentations" => "presentations#index", as: :presentations, format: "atom"
  scope "/:username" do
    get "/" => "users#show", as: :user
    get "/:slug" => "presentations#show", as: :presentation
  end
end

app/models/presentation.rb
# == Schema Information
#
# Table name: presentations
#
#  id            :integer          not null, primary key
#  user_id       :integer          not null
#  title         :string(255)      not null
#  slug          :string(255)      not null
#  is_public     :boolean          default(FALSE), not null
#  original_file :string(255)
#  pdf_file      :string(255)
#  image_file    :string(255)
#  published_at  :datetime         not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  user_id_and_is_public  (user_id,is_public)
#  user_id_and_slug       (user_id,slug) UNIQUE
#

class Presentation < ActiveRecord::Base
  include Presentation::SearchModule

  acts_as_taggable

  mount_uploader :original_file, PdfUploader
  mount_uploader :pdf_file, PdfUploader
  mount_uploader :image_file, ImageUploader

  before_validation :generate_slug

  # redis-objects override AR lock method
  class << self
    alias_method :ar_lock, :lock
  end
  include Redis::Objects
  class << self
    alias_method :redis_lock, :lock
    alias_method :lock, :ar_lock
    remove_method :ar_lock
  end
  include RedisObjectsDestroyable
  counter :access_count

  belongs_to :user
  has_one :presentation_outline, dependent: :destroy

  scope :is_public, -> { where(is_public: true) }
  scope :published_at_desc, -> { order(published_at: :desc) }

  VALID_SLUG_REGEX = /\A[0-9A-Za-z\-_]+\z/ # 英数と - _ の 2 つの半角記号
  validates :title,        presence: true
  validates :slug,         presence: true, format: { with: VALID_SLUG_REGEX, message: "英数と-_ のみで入力してください" }
  validates :published_at, presence: true

  def owner?(user)
    user_id == user.try!(:id)
  end

  def reupload(file)
    self.original_file.remove!
    self.pdf_file.remove!
    self.image_file.remove!
    self.presentation_outline.destroy

    self.original_file = file
    self.save!
    Ppt2pdfJob.perform_later(self)
  end

  private

    def generate_slug
      return if slug # generate only once

      self.slug = Zipang.to_slug(title)
      if user.presentations.where(slug: self.slug).exists?
        # slug が重複していた場合は現在時刻を付与して重複回避。
        # これで重複したら諦めてエラー
        self.slug += Time.current.strftime("%Y%m%d%H%M%S")
      end
    end
end

app/models/presentation/search_module.rb
module Presentation::SearchModule
  extend ActiveSupport::Concern

  included do # rubocop:disable Metrics/BlockLength ElasticSearch の index 定義なので無理
    include Elasticsearch::Model

    # update_document は changed_attributes に依存していて罠が多いので
    # Elasticsearch::Model::Callbacks を include せずに index_document を呼ぶ
    after_commit -> { __elasticsearch__.index_document },  on: :create
    after_commit -> { __elasticsearch__.index_document },  on: :update
    after_commit -> { __elasticsearch__.delete_document }, on: :destroy

    settings index: {
      analysis: {
        filter: {
          pos_filter: {
            type: "kuromoji_part_of_speech",
            stopgaps: ["助詞-格助詞-一般", "助詞-終助詞"],
          },
          greek_lowercase_filter: {
            type: "lowercase",
            language: "greek",
          },
        },
        analyzer: {
          kuromoji_analyzer: {
            type: "custom",
            tokenizer: "kuromoji_tokenizer",
            mode: "extended",
            filter: %w[kuromoji_baseform pos_filter greek_lowercase_filter cjk_width],
          },
        },
      },
    }
    mapping do
      indexes :title,   analyzer: :kuromoji_analyzer
      indexes :outline, analyzer: :kuromoji_analyzer
      indexes :tags,    analyzer: :kuromoji_analyzer
    end
  end

  def as_indexed_json(_options = {})
    if is_public
      {
        username: user.username,
        title: title,
        outline: presentation_outline.try(:body),
        tags: tag_list,
      }
    else
      {}
    end
  end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :authenticate_user!, if: :format_is_not_atom

  def index
    @presentations = Presentation.preload(:user).
                       is_public.
                       published_at_desc.
                       paginate(page: params[:page])

    respond_to do |format|
      format.html
      format.atom
    end
  end

  def show
    @user = User.find_by!(username: params[:username])
    @presentation = @user.presentations.is_public.find_by(slug: params[:slug])
    @presentation.access_count.increment
    render layout: nil
  end

  def search
    search_param = { query: { bool: { must: [
      { multi_match: { minimum_should_match: "100%", query: params[:q], fields: %w[tags title outline] } },
    ] } } }
    @presentations = Presentation.search(search_param).page(params[:page]).records
    render "index"
  end

  private

    def format_is_not_atom
      params[:format] != "atom"
    end
end

app/views/presentations/index.html.slim
.container
  = paginate(@presentations)

.grid
  - @presentations.each do |presentation|
    .card.grid-item.hoverable[class=("blue-grey" unless presentation.is_public)]
      .card-image.small
        - if presentation.is_public
          = link_to(presentation_path(presentation.user.username, presentation.slug)) do
            = presentation_image_tag(presentation)
        - else
          = presentation_image_tag(presentation)
      .divider
      .card-content.description
        .card-title.black-text
          = presentation.title
        .published_at
          = l(presentation.published_at, format: :date)
        - if presentation.presentation_outline
          - if params[:q]
            p = highlight(excerpt(presentation.presentation_outline.body, params[:q], radius: 100), params[:q])
          - else
            p = truncate(presentation.presentation_outline.body, length: 100)
      - unless presentation.tag_list.empty?
        .card-content
          - presentation.tag_list.each do |tag|
            = link_to(tag, tag_path(name: tag), class: "tag")
      .owner
        .page_view
          = mi("visibility", class: "margin--r5")
          = presentation.access_count.to_i
        = name_with_avatar(presentation.user)
      - if presentation.owner?(current_user)
        .card-action.right-align
          = link_to("編集", edit_manage_presentation_path(presentation))

.container
  = paginate(@presentations)