config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "admin/sidekiq"

  devise_for :users, skip: [:registration], controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    post "users",   to: "users/registrations#create", as: :user_registration
    get "sign_up",  to: "users/registrations#new",    as: :new_user_registration
    get "sign_in",  to: "devise/sessions#new",     as: :new_user_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end
  root "presentations#index"

  namespace :manage do
    resources :presentations, only: [:index, :create, :edit, :update, :destroy]
  end
  resources :tags, only: [:show], param: :name
  get "presentations/search"
  get "presentations" => "presentations#index", as: :presentations, format: "atom"
  scope "/:username" do
    get "/" => "users#show", as: :user
    get "/:slug" => "presentations#show", as: :presentation
  end
end

app/views/layouts/_header.html.slim
nav.white
  .nav-wrapper.container
    = link_to("HellShake", root_url, class: "brand-logo")
    ul.right
      li
        = form_tag(presentations_search_path, method: "GET") do
          .input-field
            = search_field_tag(:q, params[:q], placeholder: "Search", required: true)
            = label_tag(:search, class: "label-icon")
              = mi("search")
            = mi("close")

      - if current_user
        li
          = link_to(manage_presentations_path, class: "valign-wrapper")
            = image_tag(current_user.image_url, size: "32x32", class: "margin--r5 valign")
            span.valign = current_user.name

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    title
      | HellShake
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    link[rel="alternate" type="application/atom+xml" title="Atom feed" href=(presentations_url(format: :atom))]
  body
    = render "layouts/header"
    .section
      = yield
    footer.page-footer.teal
      .container
        .row
          .col.l6
            h5.white-text 使い方
            p.white-text 右のフォームからアップロードしてください
            p.white-text 数分後に PDF 化されて見られるようになります
          .col.l6
            h5.white-text アップロードフォーム
            - if current_user
              = form_for(current_user.presentations.new, url: manage_presentations_path) do |f|
                = f.file_field(:original_file)
                = f.submit "upload"
            - else
              p ログインすると使うことができます
      .footer-copyright
        .container
          | 要望は #{link_to("github の issue", "https://github.com/onk/hellshake/issues", class: "brown-text text-lighten-3")} にどうぞ